### ISSUE TITLE
CalculationParameters object doesn't set the method attribute correctly

### ISSUE THREAD

**Issue by 0xzer0x** [alphahm/adhanpy#16]
As-salamu alaykum brother, I hope you're doing well. while implementing a feature in a project that uses your library I came across a strange issue. When Trying to create a CalculationParameters object passing only fajr & isha angles. the _method_ attribute doesn't get set to **None**, resulting in an error when the _set_fajr() method tries to access this attribute. 

I've modified the example code to reproduce the same error
```python
from datetime import datetime
from zoneinfo import ZoneInfo
from adhanpy.calculation import CalculationMethod, CalculationParameters
from adhanpy.PrayerTimes import PrayerTimes


def print_prayer_times(when: datetime, prayer_times: PrayerTimes):
    format = "%H:%M"
    print(f"Prayer times for {today.strftime('%A %d %B %Y')}:")
    print(f"Fajr: {prayer_times.fajr.strftime(format)}")
    print(f"Sunrise: {prayer_times.sunrise.strftime(format)}")
    print(f"Dhuhr: {prayer_times.dhuhr.strftime(format)}")
    print(f"Asr: {prayer_times.asr.strftime(format)}")
    print(f"Maghrib: {prayer_times.maghrib.strftime(format)}")
    print(f"Isha: {prayer_times.isha.strftime(format)}")


if __name__ == "__main__":
    coordinates = (51.49799827422162, -0.1358135027951458)
    param = CalculationParameters(method=None,
                                  fajr_angle=18.0, isha_angle=18.0)  # the method parameter is set explicitly but still gives an error
    # param.method = None  # this line solves the issue 
    print(param.fajr_angle, param.isha_angle)
    today = datetime.now()
    london_zone = ZoneInfo("Europe/London")
    prayer_times = PrayerTimes(
        coordinates,
        today,
        calculation_parameters=param,
        time_zone=london_zone,
    )

    print_prayer_times(today, prayer_times)

```

**And this is the error traceback**
```sh
Traceback (most recent call last):
  File "...\test.py", line 34, in <module>
    prayer_times = PrayerTimes(
  File "[python env path]\lib\site-packages\adhanpy\PrayerTimes.py", line 115, in __init__
    self._set_fajr()
  File "[python env path]\lib\site-packages\adhanpy\PrayerTimes.py", line 132, in _set_fajr
    self.calculation_parameters.method
AttributeError: 'CalculationParameters' object has no attribute 'method'
```

**Comment by alphahm** [comment]
Wa3likum salâm ! Thanks for reporting, I have made some changes and added more tests. But really, in the long term this will need some refactoring.

**Comment by alphahm** [comment]
Nice work on your desktop application  👍
